name: actions workflow
on: [pull_request]

jobs:
  actions-workflow-one:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -al
      - name: checkout action
        uses: actions/checkout@v1
      - name: list after checkout
        run: |
          pwd
          ls -al
      - name: hello world java script
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Varadha
      - name: action ran time
        run: echo "${{steps.greet.outputs.time}}"
      - name: echo variables
        run: |
          echo $GITHUB_SHA
          echo $GITHB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"

          
      