name: use-matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: nre-node-version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-version: 6
      - name: nre-node-after
        run: node -v

