name: use-matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node-version: [8,8,10]
        include:
          - node-version: 8
            os: ubuntu-latest
            extra-variable: "true"

        exclude:
          -  os: macos-latest
             node-version: 10
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_8: ${{ matrix.extra-variable }}
    steps:
      - name: nre-node-version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: nre-node-after
        run: |
          node -v
          echo $IS_UBUNTU_8

