name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        continue-on-error: true
        run: eecho "This is my first action"
      - name: run multiple commands
        run: |
          node -v
          npm -v
      - name: third step
        run: echo "oh this one ran"
  run-shell-command-on-power:
    runs-on: ubuntu-latest
    steps:
      - name: python command
        shell: python
        run: |
          import platform
          print(platform.processor())
  run-on-windows:
    runs-on: windows-latest
    needs: ["run-shell-command","run-shell-command-on-power"]
    steps:
      - name: runs of windows
        run: Get-Location
      - name: using bash
        shell: bash
        run: pwd
      
    