name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "This is my first action"
      - name: run multiple commands
        run: |
          node -v
          npm -v